// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ipc/v1/ipc.proto

package ipcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status represents the status of an operation
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_SUCCESS     Status = 1
	Status_STATUS_ERROR       Status = 2
	Status_STATUS_PENDING     Status = 3
	Status_STATUS_CANCELLED   Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_SUCCESS",
		2: "STATUS_ERROR",
		3: "STATUS_PENDING",
		4: "STATUS_CANCELLED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_SUCCESS":     1,
		"STATUS_ERROR":       2,
		"STATUS_PENDING":     3,
		"STATUS_CANCELLED":   4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_ipc_v1_ipc_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_ipc_v1_ipc_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_ipc_v1_ipc_proto_rawDescGZIP(), []int{0}
}

// ErrorCode represents different types of errors
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED        ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_REQUEST    ErrorCode = 1
	ErrorCode_ERROR_CODE_INTERNAL_ERROR     ErrorCode = 2
	ErrorCode_ERROR_CODE_TIMEOUT            ErrorCode = 3
	ErrorCode_ERROR_CODE_NOT_FOUND          ErrorCode = 4
	ErrorCode_ERROR_CODE_PERMISSION_DENIED  ErrorCode = 5
	ErrorCode_ERROR_CODE_RESOURCE_EXHAUSTED ErrorCode = 6
	ErrorCode_ERROR_CODE_UNAVAILABLE        ErrorCode = 7
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_INVALID_REQUEST",
		2: "ERROR_CODE_INTERNAL_ERROR",
		3: "ERROR_CODE_TIMEOUT",
		4: "ERROR_CODE_NOT_FOUND",
		5: "ERROR_CODE_PERMISSION_DENIED",
		6: "ERROR_CODE_RESOURCE_EXHAUSTED",
		7: "ERROR_CODE_UNAVAILABLE",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":        0,
		"ERROR_CODE_INVALID_REQUEST":    1,
		"ERROR_CODE_INTERNAL_ERROR":     2,
		"ERROR_CODE_TIMEOUT":            3,
		"ERROR_CODE_NOT_FOUND":          4,
		"ERROR_CODE_PERMISSION_DENIED":  5,
		"ERROR_CODE_RESOURCE_EXHAUSTED": 6,
		"ERROR_CODE_UNAVAILABLE":        7,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_ipc_v1_ipc_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_ipc_v1_ipc_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_ipc_v1_ipc_proto_rawDescGZIP(), []int{1}
}

// Mode represents the initialization mode for a process
type Mode int32

const (
	Mode_MODE_UNSPECIFIED Mode = 0
	Mode_MODE_CONSUMER    Mode = 1
	Mode_MODE_WORKER      Mode = 2
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_CONSUMER",
		2: "MODE_WORKER",
	}
	Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_CONSUMER":    1,
		"MODE_WORKER":      2,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_ipc_v1_ipc_proto_enumTypes[2].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_ipc_v1_ipc_proto_enumTypes[2]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_ipc_v1_ipc_proto_rawDescGZIP(), []int{2}
}

// NetworkState represents the state of network connectivity
type NetworkState int32

const (
	NetworkState_NETWORK_STATE_UNSPECIFIED  NetworkState = 0
	NetworkState_NETWORK_STATE_DISCONNECTED NetworkState = 1
	NetworkState_NETWORK_STATE_CONNECTING   NetworkState = 2
	NetworkState_NETWORK_STATE_CONNECTED    NetworkState = 3
)

// Enum value maps for NetworkState.
var (
	NetworkState_name = map[int32]string{
		0: "NETWORK_STATE_UNSPECIFIED",
		1: "NETWORK_STATE_DISCONNECTED",
		2: "NETWORK_STATE_CONNECTING",
		3: "NETWORK_STATE_CONNECTED",
	}
	NetworkState_value = map[string]int32{
		"NETWORK_STATE_UNSPECIFIED":  0,
		"NETWORK_STATE_DISCONNECTED": 1,
		"NETWORK_STATE_CONNECTING":   2,
		"NETWORK_STATE_CONNECTED":    3,
	}
)

func (x NetworkState) Enum() *NetworkState {
	p := new(NetworkState)
	*p = x
	return p
}

func (x NetworkState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkState) Descriptor() protoreflect.EnumDescriptor {
	return file_ipc_v1_ipc_proto_enumTypes[3].Descriptor()
}

func (NetworkState) Type() protoreflect.EnumType {
	return &file_ipc_v1_ipc_proto_enumTypes[3]
}

func (x NetworkState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkState.Descriptor instead.
func (NetworkState) EnumDescriptor() ([]byte, []int) {
	return file_ipc_v1_ipc_proto_rawDescGZIP(), []int{3}
}

// Error represents an error response
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=ipc.v1.ErrorCode" json:"code,omitempty"`                                                            // The error code
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                                             // Human-readable error message
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`                                                                             // Additional error details
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_ipc_v1_ipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_v1_ipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_ipc_v1_ipc_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *Error) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// StatusResponse represents a status response
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=ipc.v1.Status" json:"status,omitempty"`                                                           // The status of the operation
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                                             // Status message
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                         // When the status was generated
	Error         *Error                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                                                                                 // Error details if status is ERROR
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_ipc_v1_ipc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_v1_ipc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_ipc_v1_ipc_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StatusResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *StatusResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// HealthCheckRequest represents a health check request
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`                                                                                 // Service name to check
	Parameters    map[string]string      `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Health check parameters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_ipc_v1_ipc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_v1_ipc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_ipc_v1_ipc_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthCheckRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// HealthCheckResponse represents a health check response
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=ipc.v1.Status" json:"status,omitempty"`                                                         // Overall health status
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`                                                                           // Service name
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                       // When the check was performed
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Health check details
	Error         *Error                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                                                                               // Error if health check failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_ipc_v1_ipc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_v1_ipc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_ipc_v1_ipc_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *HealthCheckResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// PingRequest represents a ping request
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`     // Optional ping message
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // When the ping was sent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_ipc_v1_ipc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_v1_ipc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_ipc_v1_ipc_proto_rawDescGZIP(), []int{4}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// PingResponse represents a ping response
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                       // Pong message
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                   // When the pong was sent
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"` // Latency in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_ipc_v1_ipc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_v1_ipc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_ipc_v1_ipc_proto_rawDescGZIP(), []int{5}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PingResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

// GetStatusRequest represents a request to get service status
type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`                                                                                 // Service name to get status for
	Parameters    map[string]string      `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Status check parameters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_ipc_v1_ipc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_v1_ipc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_ipc_v1_ipc_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatusRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetStatusRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// GetStatusResponse represents a response with service status
type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=ipc.v1.Status" json:"status,omitempty"`                                                           // The status of the service
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                                             // Status message
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                         // When the status was generated
	Error         *Error                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                                                                                 // Error details if status is ERROR
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_ipc_v1_ipc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_v1_ipc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_ipc_v1_ipc_proto_rawDescGZIP(), []int{7}
}

func (x *GetStatusResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *GetStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetStatusResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GetStatusResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetStatusResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GenericMessage represents a generic message structure
type GenericMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                     // Unique message ID
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                                                                 // Message type
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                                                                           // Message payload
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                       // When the message was created
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Message headers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericMessage) Reset() {
	*x = GenericMessage{}
	mi := &file_ipc_v1_ipc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericMessage) ProtoMessage() {}

func (x *GenericMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_v1_ipc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericMessage.ProtoReflect.Descriptor instead.
func (*GenericMessage) Descriptor() ([]byte, []int) {
	return file_ipc_v1_ipc_proto_rawDescGZIP(), []int{8}
}

func (x *GenericMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GenericMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GenericMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GenericMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GenericMessage) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// Initialize represents an initialization message
type Initialize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          Mode                   `protobuf:"varint,1,opt,name=mode,proto3,enum=ipc.v1.Mode" json:"mode,omitempty"` // The mode for initialization (CONSUMER or WORKER)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Initialize) Reset() {
	*x = Initialize{}
	mi := &file_ipc_v1_ipc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Initialize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Initialize) ProtoMessage() {}

func (x *Initialize) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_v1_ipc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Initialize.ProtoReflect.Descriptor instead.
func (*Initialize) Descriptor() ([]byte, []int) {
	return file_ipc_v1_ipc_proto_rawDescGZIP(), []int{9}
}

func (x *Initialize) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_UNSPECIFIED
}

// NetworkStatus represents the current network status
type NetworkStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         NetworkState           `protobuf:"varint,1,opt,name=state,proto3,enum=ipc.v1.NetworkState" json:"state,omitempty"` // Current network state
	PeerCount     int32                  `protobuf:"varint,2,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"` // Number of connected peers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkStatus) Reset() {
	*x = NetworkStatus{}
	mi := &file_ipc_v1_ipc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStatus) ProtoMessage() {}

func (x *NetworkStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_v1_ipc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStatus.ProtoReflect.Descriptor instead.
func (*NetworkStatus) Descriptor() ([]byte, []int) {
	return file_ipc_v1_ipc_proto_rawDescGZIP(), []int{10}
}

func (x *NetworkStatus) GetState() NetworkState {
	if x != nil {
		return x.State
	}
	return NetworkState_NETWORK_STATE_UNSPECIFIED
}

func (x *NetworkStatus) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

var File_ipc_v1_ipc_proto protoreflect.FileDescriptor

const file_ipc_v1_ipc_proto_rawDesc = "" +
	"\n" +
	"\x10ipc/v1/ipc.proto\x12\x06ipc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x01\n" +
	"\x05Error\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.ipc.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\x127\n" +
	"\bmetadata\x18\x04 \x03(\v2\x1b.ipc.v1.Error.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb0\x02\n" +
	"\x0eStatusResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.ipc.v1.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12#\n" +
	"\x05error\x18\x04 \x01(\v2\r.ipc.v1.ErrorR\x05error\x12@\n" +
	"\bmetadata\x18\x05 \x03(\v2$.ipc.v1.StatusResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x01\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12J\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2*.ipc.v1.HealthCheckRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x02\n" +
	"\x13HealthCheckResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.ipc.v1.StatusR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12B\n" +
	"\adetails\x18\x04 \x03(\v2(.ipc.v1.HealthCheckResponse.DetailsEntryR\adetails\x12#\n" +
	"\x05error\x18\x05 \x01(\v2\r.ipc.v1.ErrorR\x05error\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x81\x01\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\"\xb5\x01\n" +
	"\x10GetStatusRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12H\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2(.ipc.v1.GetStatusRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x02\n" +
	"\x11GetStatusResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.ipc.v1.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12#\n" +
	"\x05error\x18\x04 \x01(\v2\r.ipc.v1.ErrorR\x05error\x12C\n" +
	"\bmetadata\x18\x05 \x03(\v2'.ipc.v1.GetStatusResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x02\n" +
	"\x0eGenericMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12=\n" +
	"\aheaders\x18\x05 \x03(\v2#.ipc.v1.GenericMessage.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\n" +
	"Initialize\x12 \n" +
	"\x04mode\x18\x01 \x01(\x0e2\f.ipc.v1.ModeR\x04mode\"Z\n" +
	"\rNetworkStatus\x12*\n" +
	"\x05state\x18\x01 \x01(\x0e2\x14.ipc.v1.NetworkStateR\x05state\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x02 \x01(\x05R\tpeerCount*p\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x01\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x02\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x03\x12\x14\n" +
	"\x10STATUS_CANCELLED\x10\x04*\xf9\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aERROR_CODE_INVALID_REQUEST\x10\x01\x12\x1d\n" +
	"\x19ERROR_CODE_INTERNAL_ERROR\x10\x02\x12\x16\n" +
	"\x12ERROR_CODE_TIMEOUT\x10\x03\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x04\x12 \n" +
	"\x1cERROR_CODE_PERMISSION_DENIED\x10\x05\x12!\n" +
	"\x1dERROR_CODE_RESOURCE_EXHAUSTED\x10\x06\x12\x1a\n" +
	"\x16ERROR_CODE_UNAVAILABLE\x10\a*@\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rMODE_CONSUMER\x10\x01\x12\x0f\n" +
	"\vMODE_WORKER\x10\x02*\x88\x01\n" +
	"\fNetworkState\x12\x1d\n" +
	"\x19NETWORK_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aNETWORK_STATE_DISCONNECTED\x10\x01\x12\x1c\n" +
	"\x18NETWORK_STATE_CONNECTING\x10\x02\x12\x1b\n" +
	"\x17NETWORK_STATE_CONNECTED\x10\x032\xc9\x01\n" +
	"\n" +
	"IPCService\x121\n" +
	"\x04Ping\x12\x13.ipc.v1.PingRequest\x1a\x14.ipc.v1.PingResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.ipc.v1.HealthCheckRequest\x1a\x1b.ipc.v1.HealthCheckResponse\x12@\n" +
	"\tGetStatus\x12\x18.ipc.v1.GetStatusRequest\x1a\x19.ipc.v1.GetStatusResponseB\x81\x01\n" +
	"\n" +
	"com.ipc.v1B\bIpcProtoP\x01Z0github.com/crowdllama/crowdllama-pb/ipc/v1;ipcv1\xa2\x02\x03IXX\xaa\x02\x06Ipc.V1\xca\x02\x06Ipc\\V1\xe2\x02\x12Ipc\\V1\\GPBMetadata\xea\x02\aIpc::V1b\x06proto3"

var (
	file_ipc_v1_ipc_proto_rawDescOnce sync.Once
	file_ipc_v1_ipc_proto_rawDescData []byte
)

func file_ipc_v1_ipc_proto_rawDescGZIP() []byte {
	file_ipc_v1_ipc_proto_rawDescOnce.Do(func() {
		file_ipc_v1_ipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ipc_v1_ipc_proto_rawDesc), len(file_ipc_v1_ipc_proto_rawDesc)))
	})
	return file_ipc_v1_ipc_proto_rawDescData
}

var file_ipc_v1_ipc_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_ipc_v1_ipc_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_ipc_v1_ipc_proto_goTypes = []any{
	(Status)(0),                   // 0: ipc.v1.Status
	(ErrorCode)(0),                // 1: ipc.v1.ErrorCode
	(Mode)(0),                     // 2: ipc.v1.Mode
	(NetworkState)(0),             // 3: ipc.v1.NetworkState
	(*Error)(nil),                 // 4: ipc.v1.Error
	(*StatusResponse)(nil),        // 5: ipc.v1.StatusResponse
	(*HealthCheckRequest)(nil),    // 6: ipc.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 7: ipc.v1.HealthCheckResponse
	(*PingRequest)(nil),           // 8: ipc.v1.PingRequest
	(*PingResponse)(nil),          // 9: ipc.v1.PingResponse
	(*GetStatusRequest)(nil),      // 10: ipc.v1.GetStatusRequest
	(*GetStatusResponse)(nil),     // 11: ipc.v1.GetStatusResponse
	(*GenericMessage)(nil),        // 12: ipc.v1.GenericMessage
	(*Initialize)(nil),            // 13: ipc.v1.Initialize
	(*NetworkStatus)(nil),         // 14: ipc.v1.NetworkStatus
	nil,                           // 15: ipc.v1.Error.MetadataEntry
	nil,                           // 16: ipc.v1.StatusResponse.MetadataEntry
	nil,                           // 17: ipc.v1.HealthCheckRequest.ParametersEntry
	nil,                           // 18: ipc.v1.HealthCheckResponse.DetailsEntry
	nil,                           // 19: ipc.v1.GetStatusRequest.ParametersEntry
	nil,                           // 20: ipc.v1.GetStatusResponse.MetadataEntry
	nil,                           // 21: ipc.v1.GenericMessage.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
}
var file_ipc_v1_ipc_proto_depIdxs = []int32{
	1,  // 0: ipc.v1.Error.code:type_name -> ipc.v1.ErrorCode
	15, // 1: ipc.v1.Error.metadata:type_name -> ipc.v1.Error.MetadataEntry
	0,  // 2: ipc.v1.StatusResponse.status:type_name -> ipc.v1.Status
	22, // 3: ipc.v1.StatusResponse.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 4: ipc.v1.StatusResponse.error:type_name -> ipc.v1.Error
	16, // 5: ipc.v1.StatusResponse.metadata:type_name -> ipc.v1.StatusResponse.MetadataEntry
	17, // 6: ipc.v1.HealthCheckRequest.parameters:type_name -> ipc.v1.HealthCheckRequest.ParametersEntry
	0,  // 7: ipc.v1.HealthCheckResponse.status:type_name -> ipc.v1.Status
	22, // 8: ipc.v1.HealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	18, // 9: ipc.v1.HealthCheckResponse.details:type_name -> ipc.v1.HealthCheckResponse.DetailsEntry
	4,  // 10: ipc.v1.HealthCheckResponse.error:type_name -> ipc.v1.Error
	22, // 11: ipc.v1.PingRequest.timestamp:type_name -> google.protobuf.Timestamp
	22, // 12: ipc.v1.PingResponse.timestamp:type_name -> google.protobuf.Timestamp
	19, // 13: ipc.v1.GetStatusRequest.parameters:type_name -> ipc.v1.GetStatusRequest.ParametersEntry
	0,  // 14: ipc.v1.GetStatusResponse.status:type_name -> ipc.v1.Status
	22, // 15: ipc.v1.GetStatusResponse.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 16: ipc.v1.GetStatusResponse.error:type_name -> ipc.v1.Error
	20, // 17: ipc.v1.GetStatusResponse.metadata:type_name -> ipc.v1.GetStatusResponse.MetadataEntry
	22, // 18: ipc.v1.GenericMessage.timestamp:type_name -> google.protobuf.Timestamp
	21, // 19: ipc.v1.GenericMessage.headers:type_name -> ipc.v1.GenericMessage.HeadersEntry
	2,  // 20: ipc.v1.Initialize.mode:type_name -> ipc.v1.Mode
	3,  // 21: ipc.v1.NetworkStatus.state:type_name -> ipc.v1.NetworkState
	8,  // 22: ipc.v1.IPCService.Ping:input_type -> ipc.v1.PingRequest
	6,  // 23: ipc.v1.IPCService.HealthCheck:input_type -> ipc.v1.HealthCheckRequest
	10, // 24: ipc.v1.IPCService.GetStatus:input_type -> ipc.v1.GetStatusRequest
	9,  // 25: ipc.v1.IPCService.Ping:output_type -> ipc.v1.PingResponse
	7,  // 26: ipc.v1.IPCService.HealthCheck:output_type -> ipc.v1.HealthCheckResponse
	11, // 27: ipc.v1.IPCService.GetStatus:output_type -> ipc.v1.GetStatusResponse
	25, // [25:28] is the sub-list for method output_type
	22, // [22:25] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_ipc_v1_ipc_proto_init() }
func file_ipc_v1_ipc_proto_init() {
	if File_ipc_v1_ipc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ipc_v1_ipc_proto_rawDesc), len(file_ipc_v1_ipc_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ipc_v1_ipc_proto_goTypes,
		DependencyIndexes: file_ipc_v1_ipc_proto_depIdxs,
		EnumInfos:         file_ipc_v1_ipc_proto_enumTypes,
		MessageInfos:      file_ipc_v1_ipc_proto_msgTypes,
	}.Build()
	File_ipc_v1_ipc_proto = out.File
	file_ipc_v1_ipc_proto_goTypes = nil
	file_ipc_v1_ipc_proto_depIdxs = nil
}
