name: Protobuf CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  protobuf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install buf
        run: |
          curl -sSL \
            "https://github.com/bufbuild/buf/releases/latest/download/buf-$(uname -s)-$(uname -m)" \
            -o "buf" \
            && chmod +x "buf" \
            && sudo mv "buf" /usr/local/bin/

      - name: Install buf dependencies
        run: buf dep update

      - name: Check buf format
        run: buf format --diff --exit-code

      - name: Lint protobuf files
        run: buf lint

      - name: Check for breaking changes
        run: buf breaking --against '.git#branch=main'

      - name: Generate code
        run: buf generate

      - name: Check if generated files are up to date
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Generated files are not up to date. Please run 'buf generate' and commit the changes."
            git status
            exit 1
          fi 